name: CursedMinecraft
version: 1.0
main: d3v.nikkio.cursedMinecraft.CursedMinecraft
commands:
  amnesia:
    description: Applies the amnesia effect to the player
    usage: /<command> <player>
  rtp:
    description: Randomly teleports the player
    usage: /<command> <player>